DROP DATABASE IF EXISTS quizzes;

CREATE DATABASE quizzes
  WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_Europe.1252'
    LC_CTYPE = 'English_Europe.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE question (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  text varchar(1000) NOT NULL CHECK(text != '')
);

CREATE TABLE answer (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  text varchar(1000) NOT NULL CHECK(text != ''),
  is_correct boolean NOT NULL DEFAULT false,
  question_id bigint,
  CONSTRAINT fk_question
    FOREIGN KEY(question_id)
      REFERENCES question(id)
      ON DELETE CASCADE
);

CREATE TABLE tag (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  text varchar(255) NOT NULL UNIQUE
);

CREATE TABLE question_tags (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  question_id bigint,
  tag_id bigint,
  CONSTRAINT fk_question
    FOREIGN KEY(question_id)
      REFERENCES question(id)
      ON DELETE CASCADE,
  CONSTRAINT fk_tag
    FOREIGN KEY(tag_id)
      REFERENCES tag(id)
      ON DELETE CASCADE
);

INSERT INTO question(id, text)
VALUES (1, 'What is a correct syntax to output "Hello World" in Java?');

INSERT INTO answer(id, text, is_correct, question_id)
VALUES (1, 'Console.WriteLine("Hello World");', false, 1);

INSERT INTO answer(id, text, is_correct, question_id)
VALUES (2, 'print ("Hello World");', false, 1);

INSERT INTO answer(id, text, is_correct, question_id)
VALUES (3, 'echo("Hello World");', false, 1);

INSERT INTO answer(id, text, is_correct, question_id)
VALUES (4, 'System.out.println("Hello World");', true, 1);

INSERT INTO tag(id, text) VALUES (1, 'syntax');

INSERT INTO question_tags(id ,question_id, tag_id) VALUES (1, 1, 1);
