drop database if exists quizzes;

create database quizzes
  with
    owner = postgres
    encoding = 'utf8'
    lc_collate = 'english_europe.1252'
    lc_ctype = 'english_europe.1252'
    tablespace = pg_default
    connection limit = -1
    is_template = false;

create table question (
  id bigint generated by default as identity,
  content varchar(1000) not null,
  constraint pk_question_id primary key(id),
  constraint chk_question_content_not_empty check(content != '')
);

create table answer (
  id bigint generated by default as identity,
  content varchar(1000) not null,
  is_correct boolean not null,
  question_id bigint not null,
  constraint pk_answer_id primary key(id),
  constraint chk_answer_content_not_empty check(content != ''),
  constraint fk_answer_question_id
    foreign key(question_id)
      references question(id)
      on delete cascade
);

create table tag (
  id bigint generated by default as identity,
  name varchar(255) not null,
  constraint pk_tag_id primary key(id),
  constraint uq_tag_name unique(name),
  constraint chk_tag_name_not_empty check(name != '')
);

create table question_tag (
  id bigint generated by default as identity,
  question_id bigint not null,
  tag_id bigint not null,
  constraint uq_question_tag_question_id_tag_id unique(question_id, tag_id),
  constraint pk_question_tag_id primary key(id),
  constraint fk_question_tag_question_id
    foreign key(question_id)
      references question(id)
      on delete cascade,
  constraint fk_question_tag_tag_id
    foreign key(tag_id)
      references tag(id)
      on delete cascade
);

insert into question(id, content)
values (1, 'what is the correct syntax to output "hello world" in java?');

insert into answer(id, content, is_correct, question_id)
values (1, 'console.writeline("hello world");', false, 1),
       (2, 'print ("hello world");', false, 1),
       (3, 'echo("hello world");', false, 1),
       (4, 'system.out.println("hello world");', true, 1);

insert into tag(id, name) values (1, 'syntax');

insert into question_tag(id, question_id, tag_id) values (1, 1, 1);
